# March Machine Learning Mania 2026 v3 — Optuna-Tuned Stacking Ensemble
#
# Strategy (v2 preserved + 8 new features):
# - Rating systems: Elo, Glicko-2, Bradley-Terry, Colley Matrix
# - Pythagorean win% (exponent=11.5)
# - Coach tournament experience (MTeamCoaches.csv)
# - Conference tournament performance (MConferenceTourneyGames.csv)
# - SOS-adjusted efficiency
# - Optuna HPO: 40 trials x LightGBM/XGBoost/CatBoost
# - Stacking meta-learner (LogisticRegression)
# - Optuna visualization (hyperparameter importance, optimization history)
# - Multi-seed ensemble with rank averaging
#
# Evaluation: Log Loss
# Competition: march-machine-learning-mania-2026
#
# Generated by generate_notebook_v3.py
