# S6E3 Predict Customer Churn — Optuna-Tuned Multi-Model Stacking
#
# Strategy:
# - Heavy feature engineering: target encoding (CV-aware), interactions, polynomial, frequency, aggregates
# - Multi-model: LightGBM + XGBoost + CatBoost, each with Optuna HPO (60 trials)
# - Multi-seed ensemble: 5 seeds x 3 models x 10 folds = 150 models
# - Stacking: OOF -> LogisticRegression meta-learner
# - Final: Rank averaging of all 4 predictions
# - W&B offline tracking
#
# Evaluation: ROC AUC
# Competition: playground-series-s6e3
#
# Generated by generate_notebook.py
