"""Write kernels/<name>/ = this fp2 kernel with another seed / epoch count (ensemble members).

Kaggle kernels take no environment, so the defaults are baked into a copy:

    python enveda-casmi26/kernels/fp2/make_variant.py fp2s1 1 16 [D]
"""
import json
import os
import sys

name, seed, epochs = sys.argv[1], sys.argv[2], sys.argv[3]
d_model = sys.argv[4] if len(sys.argv) > 4 else "384"
here = os.path.dirname(os.path.abspath(__file__))
out = os.path.join(here, "..", name)
os.makedirs(out, exist_ok=True)
src = open(os.path.join(here, "main.py"), encoding="utf-8").read()
src = src.replace('os.environ.get("FP2_SEED", "0")', f'os.environ.get("FP2_SEED", "{seed}")', 1)
src = src.replace('os.environ.get("FP2_EPOCHS", "16")', f'os.environ.get("FP2_EPOCHS", "{epochs}")', 1)
src = src.replace('os.environ.get("FP2_D", "384")', f'os.environ.get("FP2_D", "{d_model}")', 1)
src = src.replace('"""CASMI26 FP2:', f'"""CASMI26 FP2 (generated by fp2/make_variant.py: seed {seed}, {epochs} epochs, d {d_model}):', 1)
open(os.path.join(out, "main.py"), "w", encoding="utf-8").write(src)
meta = json.load(open(os.path.join(here, "kernel-metadata.json")))
meta["id"] = f"yasunorim/casmi26-{name}"
meta["title"] = f"casmi26 {name}"
json.dump(meta, open(os.path.join(out, "kernel-metadata.json"), "w"), indent=2)
print("wrote", out)
