#!/usr/bin/env python
"""Split a recorded plan in half and let the policy own the other half.

A naked replay memorises. Measured 2026-08-25 (run 32840601092) with twelve
training seeds instead of four: training money rose 62,604 -> 70,989 over 62
generations while the held-out paired difference went -2,125 -> -3,127 and
never once cleared zero. Tripling the seeds did not close the gap, so the
transfer failure is not a sampling problem.

Where does it live? A plan is two very different things stapled together:

* labour -- the farmer and the hands, a whole-day routing question that a
  per-turn greedy policy demonstrably cannot answer (43% of the top plan's
  actions are steps against this farm's 53%), and
* market -- SELL and BUY orders, which depend on what is *in the shed this
  turn*. Recorded quantities are timings, and a different season ripens on
  different turns, so every one of them lands wrong.

The top published replay does not replay its market orders naively either: its
`_front_run` reads the live shed and the town's demand and rewrites the sell
book. Our replay has no such layer, and our own policy already prices better
than it does on four of six goods (strawberry 103.8 to their 84.4, melon 236.7
to 115.0, milk 88.5 to 78.2, wheat 44.8 to 41.8, measured on seed 3000).

So: emit an agent that takes labour from the plan and the market from the
policy -- and, as the control, one that does the opposite. If the first
transfers and the second does not, the memorisation is in the order book and
the labour plan is worth optimising on its own. If neither does, it is in the
routing, and this whole road is about the plan's labour after all.

The output is one file with no imports, the same shape as emit_sched.py: the
policy's own source, then the plan, then a wrapper that rebinds `agent`. The
original entry point is captured under another name first, so nothing is
edited in place.

Usage:
    python sim/emit_mix.py plan.json --half labour --out agents/mix_labour.py
    python sim/emit_mix.py plan.json --half market --out agents/mix_market.py
"""
import argparse
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

TAIL = '''

# ---------------------------------------------------------------------------
# Half a recorded plan, bound after the definitions above. Generated by
# sim/emit_mix.py -- edit the plan, not this file.
#
# HALF = "labour": the farmer and hands come from the plan, the market orders
#        from the policy, which reads the shed this turn.
# HALF = "market": the reverse, as the control.
import json as _json          # main.py imports math and nothing else
_POLICY_AGENT = agent
# kaggle_environments picks the module's LAST-INSERTED callable as the agent,
# and a name that already exists keeps its original position in the namespace
# dict -- rebinding `agent` at the end of the file does not move it. So the
# helper defined below would be picked instead, and called with (observation,
# configuration): `turns_per_day` became a Struct and every episode died at
# step 2 with the farm still empty, reading as an agent that scores exactly
# its starting cash. Dropping the name first makes the definition below a
# fresh insertion, which puts it last where the loader looks.
#
# emit_sched.py does not hit this because it appends no callables at all.
del agent
HALF = "__HALF__"
_PLAN = _json.loads(r\'\'\'__PLAN__\'\'\')
__NOTE__

def _mix_step(obs, turns_per_day=24):
    """Which step this is.

    The environment writes `day` and `hour` onto every observation, and `step`
    is only a fallback. Getting it wrong is silent and total -- a replay stuck
    on step 0 re-issues the opening turn 720 times and hires on every one.
    """
    day = g(obs, "day", None)
    hour = g(obs, "hour", None)
    if day is not None and hour is not None:
        return int(day) * turns_per_day + int(hour)
    return int(g(obs, "step", 0) or 0)


def agent(obs, config=None):
    # The policy runs on every turn whichever half is used, because it carries
    # the per-turn memory (_MEM) that its own assignment rule reads next turn.
    # Skipping it on the turns the plan owns would quietly change the policy
    # into a different agent, and then the control would not be a control.
    policy = _POLICY_AGENT(obs, config)
    try:
        step = min(max(0, _mix_step(obs)), len(_PLAN) - 1)
        planned = _PLAN[step]
        me = int(g(obs, "player", 0) or 0)
        farms = g(obs, "farms", []) or []
        farm = farms[me] if me < len(farms) else {}
        n_hands = len(g(farm, "hands", []) or [])
        if HALF == "labour":
            hands = [list(h) for h in (planned.get("hands") or [])][:n_hands]
            while len(hands) < n_hands:
                hands.append(["PASS"])
            return {"farmer": list(planned.get("farmer", ["PASS"])),
                    "hands": hands,
                    "market": policy.get("market", [])}
        return {"farmer": policy.get("farmer", ["PASS"]),
                "hands": policy.get("hands", []),
                "market": [list(o) for o in (planned.get("market") or [])][:10]}
    except Exception:
        # A broken plan must not be scored as a broken policy: fall all the way
        # back rather than returning half an action.
        return policy
'''


def emit(plan, half, main_path=None, note=""):
    main_path = main_path or os.path.join(ROOT, "main.py")
    with open(main_path, encoding="utf-8") as f:
        source = f.read()
    assert "\ndef agent(obs, config=None):" in source, "main.py has no agent hook"
    assert "^^^" not in json.dumps(plan), "plan carries the delimiter"
    tail = TAIL.replace("__HALF__", half)
    tail = tail.replace("__PLAN__", json.dumps(plan, separators=(",", ":")))
    tail = tail.replace("__NOTE__",
                        "\n".join("# " + ln for ln in note.splitlines()) if note else "")
    return source + tail


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("plan")
    ap.add_argument("--half", choices=("labour", "market"), required=True)
    ap.add_argument("--main", default="")
    ap.add_argument("--note", default="")
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    with open(args.plan, encoding="utf-8") as f:
        plan = json.load(f)
    assert isinstance(plan, list) and plan, "plan is not a list of steps"
    src = emit(plan, args.half, args.main or None, args.note)
    with open(args.out, "w", encoding="utf-8", newline="\n") as f:
        f.write(src)
    print(f"wrote {args.out}  half={args.half}  steps={len(plan)}")


if __name__ == "__main__":
    main()
