#!/usr/bin/env python
"""Turn a calendar into a submittable agent.

The agent is main.py with the calendar bound to its SCHEDULE global, appended
as a literal at the end of the file. Appending works because _sched_for reads
the global at call time, so a rebinding after the function definitions is in
force before the first turn -- and it leaves main.py's own source untouched,
which matters because main.py is the opponent every sweep is measured against.

One file, no imports, no data file to ship alongside: the same shape Kaggle
wants and the same shape the replay agents use.

Usage:
    python sim/emit_sched.py schedules/blueprint.json --out agents/v17_sched.py
"""
import argparse
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import schedule as sched_mod            # noqa: E402


def emit(sched, main_path=None, note=""):
    main_path = main_path or os.path.join(ROOT, "main.py")
    with open(main_path, encoding="utf-8") as f:
        source = f.read()
    assert "SCHEDULE = None" in source, "main.py has no schedule hook"
    tail = [
        "",
        "",
        "# ---------------------------------------------------------------------",
        "# Capital calendar, bound after the definitions above so it is in force",
        "# before the first turn. Generated by sim/emit_sched.py -- edit the",
        "# calendar, not this file.",
    ]
    if note:
        tail += ["# " + line for line in note.splitlines()]
    tail += ["SCHEDULE = " + json.dumps(sched, sort_keys=True), ""]
    return source + "\n".join(tail)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("sched")
    ap.add_argument("--main", default="")
    ap.add_argument("--note", default="")
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    with open(args.sched, encoding="utf-8") as f:
        sched = json.load(f)
    sched_mod.validate(sched)
    text = emit(sched, args.main or None, args.note)

    out_dir = os.path.dirname(os.path.abspath(args.out))
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(text)

    # An agent that does not import is not an agent. Check it here rather than
    # three hours into a job.
    import importlib.util
    spec = importlib.util.spec_from_file_location("emitted_check", args.out)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    assert mod.SCHEDULE == sched, "the emitted agent lost its calendar"
    assert callable(mod.agent), "the emitted agent has no agent()"
    print("wrote %s (%d bytes), calendar of %d entries, imports clean"
          % (args.out, len(text), len(sched)))
    sched_mod.dump(sched, args.out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
