#!/usr/bin/env python
"""Turn a calendar into a submittable agent.

The agent is main.py with the calendar bound to its SCHEDULE global, appended
as a literal at the end of the file. Appending works because _sched_for reads
the global at call time, so a rebinding after the function definitions is in
force before the first turn -- and it leaves main.py's own source untouched,
which matters because main.py is the opponent every sweep is measured against.

One file, no imports, no data file to ship alongside: the same shape Kaggle
wants and the same shape the replay agents use.

Usage:
    python sim/emit_sched.py schedules/blueprint.json --out agents/v17_sched.py
"""
import argparse
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import schedule as sched_mod            # noqa: E402


def py_literal(d):
    """A Python dict literal, sorted.

    Not json.dumps. The file this goes into is imported, not parsed, and JSON
    writes `true`/`false`/`null` -- so a boolean override produced an agent
    that died on its first import with

        NameError: name 'true' is not defined

    It sat here unseen because the only agent anyone had ever rebuilt carried
    a calendar and one float, and sim/test_reemit.py defaulted to that same
    agent, so the round trip was green on a case that could not fail.
    """
    return "{" + ", ".join(f"{k!r}: {d[k]!r}" for k in sorted(d)) + "}"


def emit(sched, main_path=None, note=""):
    main_path = main_path or os.path.join(ROOT, "main.py")
    with open(main_path, encoding="utf-8") as f:
        source = f.read()
    assert "SCHEDULE = None" in source, "main.py has no schedule hook"
    tail = [
        "",
        "",
        "# ---------------------------------------------------------------------",
        "# Capital calendar, bound after the definitions above so it is in force",
        "# before the first turn. Generated by sim/emit_sched.py -- edit the",
        "# calendar, not this file.",
    ]
    if note:
        tail += ["# " + line for line in note.splitlines()]
    tail += ["SCHEDULE = " + json.dumps(sched, sort_keys=True), ""]
    return source + "\n".join(tail)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("sched")
    ap.add_argument("--main", default="")
    ap.add_argument("--note", default="")
    # Knob overrides, appended as a P.update() after the calendar -- the shape
    # v25_global.py already uses. A calendar climbed under one setting is not
    # automatically right under another, so this is a way to build the
    # candidate, not a claim that it transfers: measure it head-to-head
    # against the incumbent before believing it.
    ap.add_argument("--set", default="",
                    help='JSON object of P overrides, e.g. \'{"dist_weight": 1.0}\'')
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    with open(args.sched, encoding="utf-8") as f:
        sched = json.load(f)
    sched_mod.validate(sched)
    text = emit(sched, args.main or None, args.note)
    if args.set:
        over = json.loads(args.set)
        assert isinstance(over, dict) and over, "--set must be a non-empty object"
        # Refuse a name the agent does not carry: a P.update() that invents a
        # key is a knob nobody reads, and it reads downstream as a clean tie.
        have = set(re.findall(r'^\s{4}"([A-Za-z_]+)"\s*:', text, re.M))
        missing = sorted(k for k in over if k not in have)
        assert not missing, f"agent has no such knob(s): {', '.join(missing)}"
        text += ("\n# Knob overrides from sim/emit_sched.py --set\n"
                 "P.update(" + py_literal(over) + ")\n")

    out_dir = os.path.dirname(os.path.abspath(args.out))
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(text)

    # An agent that does not import is not an agent. Check it here rather than
    # three hours into a job.
    import importlib.util
    spec = importlib.util.spec_from_file_location("emitted_check", args.out)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    assert mod.SCHEDULE == sched, "the emitted agent lost its calendar"
    assert callable(mod.agent), "the emitted agent has no agent()"
    print("wrote %s (%d bytes), calendar of %d entries, imports clean"
          % (args.out, len(text), len(sched)))
    sched_mod.dump(sched, args.out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
