#!/usr/bin/env python
"""Record one episode's action list from an agent, and replay it back.

Why this exists: every strong published agent in this competition is a replay.
It ships a fixed 720-step action list and returns `plan[step]` each turn, with
a thin repair layer for the parts the season randomises. Decoding one showed
why that wins -- its labour spends 43% of actions walking against this farm's
63%, and 967 of them on CARE against 169 -- and a per-turn greedy policy cannot
reach that, because the route a hand should walk is a whole-day question.

So the plan itself has to become the object that gets optimised. This module
is the two halves that makes that possible:

* `record` plays an agent and writes what it actually did, step by step;
* `emit` turns such a list into a standalone agent file that replays it.

Nothing here decides anything: the search that improves a recorded plan lives
in optimize.py, and it uses evaluate.py to score each candidate.

Usage:
    python sim/record.py --a main.py --b starter --seed 3000 --out plan.json
    python sim/record.py --emit plan.json --out agents/plan_agent.py
"""
import argparse
import json
import os
import sys

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

REPLAY_TEMPLATE = '''"""Replay of a recorded plan (generated by sim/record.py -- do not hand-edit).

The plan is a list of one action dict per step. Two things are repaired at run
time, because both are drawn per season and a fixed list cannot know them:

* the roster: the hands list is padded or trimmed to however many hands the
  farm actually has this turn, so an action never lands on a hand that is not
  there;
* a unit standing on a tile the plan did not expect: only the market orders are
  kept in that case, which is the half of the turn that still applies.
"""
import json

PLAN = json.loads(r\'\'\'__PLAN__\'\'\')


def _get(o, k, d=None):
    if o is None:
        return d
    if isinstance(o, dict):
        return o.get(k, d)
    return getattr(o, k, d)


def agent(obs, config=None):
    try:
        step = int(_get(obs, "step", 0) or 0)
        step = min(max(0, step), len(PLAN) - 1)
        planned = PLAN[step]
        me = int(_get(obs, "player", 0) or 0)
        farms = _get(obs, "farms", []) or []
        farm = farms[me] if me < len(farms) else {}
        n_hands = len(_get(farm, "hands", []) or [])
        hands = [list(h) for h in (planned.get("hands") or [])][:n_hands]
        while len(hands) < n_hands:
            hands.append(["PASS"])
        return {"farmer": list(planned.get("farmer", ["PASS"])),
                "hands": hands,
                "market": [list(o) for o in (planned.get("market") or [])][:10]}
    except Exception:
        farms = _get(obs, "farms", []) or []
        me = int(_get(obs, "player", 0) or 0)
        farm = farms[me] if me < len(farms) else {}
        return {"farmer": ["PASS"],
                "hands": [["PASS"] for _ in (_get(farm, "hands", []) or [])],
                "market": []}
'''


def record(agent_a, agent_b, seed, steps, a_side):
    """Play one episode and return (plan, money) from A's point of view."""
    from kaggle_environments import make
    order = [agent_a, agent_b] if a_side == 0 else [agent_b, agent_a]
    env = make("kaggriculture", configuration={"episodeSteps": steps, "seed": seed})
    env.run(order)
    plan = []
    for state in env.steps:
        action = getattr(state[a_side], "action", None)
        if not isinstance(action, dict):
            action = {"farmer": ["PASS"], "hands": [], "market": []}
        plan.append({
            "farmer": list(action.get("farmer") or ["PASS"]),
            "hands": [list(h) for h in (action.get("hands") or [])],
            "market": [list(o) for o in (action.get("market") or [])],
        })
    money = float(env.steps[-1][a_side].reward or 0)
    return plan, money


def describe(plan):
    """What is actually in a recorded plan.

    A replay that scores zero looks the same whether the recording came out
    empty or the template is broken, and the two need opposite fixes. These
    counts separate them: a plan whose every step is a bare PASS with no market
    orders was never recorded, however many steps long it is.
    """
    filled = sum(1 for a in plan if (a.get("farmer") or ["PASS"])[0] != "PASS")
    hands = sum(len(a.get("hands") or []) for a in plan)
    orders = sum(len(a.get("market") or []) for a in plan)
    first = next((i for i, a in enumerate(plan)
                  if (a.get("farmer") or ["PASS"])[0] != "PASS"
                  or (a.get("market") or [])), None)
    last = next((len(plan) - 1 - i for i, a in enumerate(reversed(plan))
                 if (a.get("farmer") or ["PASS"])[0] != "PASS"
                 or (a.get("market") or [])), None)
    return (f"steps={len(plan)} farmer-acting={filled} hand-slots={hands} "
            f"market-orders={orders} first-active={first} last-active={last}")


def emit(plan, out_path):
    body = REPLAY_TEMPLATE.replace("__PLAN__", json.dumps(plan))
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(body)
    return out_path


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--a", help="agent to record (path under kaggriculture/)")
    ap.add_argument("--b", default="starter", help="opponent")
    ap.add_argument("--seed", type=int, default=3000)
    ap.add_argument("--steps", type=int, default=720)
    ap.add_argument("--side", type=int, default=0, choices=(0, 1))
    ap.add_argument("--emit", help="plan JSON to turn into an agent file")
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    if args.emit:
        with open(args.emit, encoding="utf-8") as f:
            plan = json.load(f)
        print("EMITTED", emit(plan, args.out), "steps", len(plan))
        return 0

    if not args.a:
        ap.error("--a is required unless --emit is given")
    plan, money = record(os.path.join(HERE, args.a) if os.path.exists(
        os.path.join(HERE, args.a)) else args.a, args.b, args.seed,
        args.steps, args.side)
    with open(args.out, "w", encoding="utf-8") as f:
        json.dump(plan, f)
    print(f"RECORDED money={money:.0f} -> {args.out}")
    print("PLAN " + describe(plan))
    return 0


if __name__ == "__main__":
    sys.exit(main())
