#!/usr/bin/env python
"""Record one episode's action list from an agent, and replay it back.

Why this exists: every strong published agent in this competition is a replay.
It ships a fixed 720-step action list and returns `plan[step]` each turn, with
a thin repair layer for the parts the season randomises. Decoding one showed
why that wins -- its labour spends 43% of actions walking against this farm's
63%, and 967 of them on CARE against 169 -- and a per-turn greedy policy cannot
reach that, because the route a hand should walk is a whole-day question.

So the plan itself has to become the object that gets optimised. This module
is the two halves that makes that possible:

* `record` plays an agent and writes what it actually did, step by step;
* `emit` turns such a list into a standalone agent file that replays it.

Nothing here decides anything: the search that improves a recorded plan lives
in optimize.py, and it uses evaluate.py to score each candidate.

Usage:
    python sim/record.py --a main.py --b starter --seed 3000 --out plan.json
    python sim/record.py --emit plan.json --out agents/plan_agent.py
"""
import argparse
import json
import os
import sys

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

REPLAY_TEMPLATE = '''"""Replay of a recorded plan (generated by sim/record.py -- do not hand-edit).

The plan is a list of one action dict per step, so everything depends on
knowing which step this is. The environment writes `day` and `hour` onto every
player's observation on every turn (the interpreter sets both at the end of
each step and copies them to the other agents), so the step is recovered from
those; `step` is only a fallback. Getting this wrong is silent and total: a
replay stuck on step 0 re-issues the opening turn 720 times, hires on every one
of them and ends the season with nothing.

The roster is repaired too: the hands list is padded or trimmed to however many
hands the farm actually has this turn, so an action never lands on a hand that
is not there.
"""
import json

PLAN = json.loads(r\'\'\'__PLAN__\'\'\')


def _get(o, k, d=None):
    if o is None:
        return d
    if isinstance(o, dict):
        return o.get(k, d)
    return getattr(o, k, d)


def which_step(obs, turns_per_day=24):
    day = _get(obs, "day", None)
    hour = _get(obs, "hour", None)
    if day is not None and hour is not None:
        return int(day) * turns_per_day + int(hour)
    return int(_get(obs, "step", 0) or 0)


def agent(obs, config=None):
    try:
        step = min(max(0, which_step(obs)), len(PLAN) - 1)
        planned = PLAN[step]
        me = int(_get(obs, "player", 0) or 0)
        farms = _get(obs, "farms", []) or []
        farm = farms[me] if me < len(farms) else {}
        n_hands = len(_get(farm, "hands", []) or [])
        hands = [list(h) for h in (planned.get("hands") or [])][:n_hands]
        while len(hands) < n_hands:
            hands.append(["PASS"])
        return {"farmer": list(planned.get("farmer", ["PASS"])),
                "hands": hands,
                "market": [list(o) for o in (planned.get("market") or [])][:10]}
    except Exception:
        farms = _get(obs, "farms", []) or []
        me = int(_get(obs, "player", 0) or 0)
        farm = farms[me] if me < len(farms) else {}
        return {"farmer": ["PASS"],
                "hands": [["PASS"] for _ in (_get(farm, "hands", []) or [])],
                "market": []}
'''


def record(agent_a, agent_b, seed, steps, a_side):
    """Play one episode and return (plan, money) from A's point of view."""
    from kaggle_environments import make
    order = [agent_a, agent_b] if a_side == 0 else [agent_b, agent_a]
    env = make("kaggriculture", configuration={"episodeSteps": steps, "seed": seed})
    env.run(order)
    # `env.steps[t][i].action` is the action that *produced* state t, so it was
    # decided while looking at state t-1. Recording it at index t shifts the
    # whole plan a turn late, and a turn late is fatal rather than merely
    # worse: sowing lands after the seed is gone, watering after the day has
    # rolled, and the farm earns nothing while the roster still gets hired --
    # which is how a replay of a 78,083 season finished on exactly zero. The
    # tell is that index 0 carries no action at all, because nothing preceded
    # the initial state.
    def as_action(state):
        raw = getattr(state[a_side], "action", None)
        if not isinstance(raw, dict):
            return {"farmer": ["PASS"], "hands": [], "market": []}
        return {"farmer": list(raw.get("farmer") or ["PASS"]),
                "hands": [list(h) for h in (raw.get("hands") or [])],
                "market": [list(o) for o in (raw.get("market") or [])]}

    plan = [as_action(s) for s in env.steps[1:]]
    # The final state's own action was never taken, so the last turn is idle.
    plan.append({"farmer": ["PASS"], "hands": [], "market": []})
    money = float(env.steps[-1][a_side].reward or 0)
    return plan, money


def describe(plan):
    """What is actually in a recorded plan.

    A replay that scores zero looks the same whether the recording came out
    empty or the template is broken, and the two need opposite fixes. These
    counts separate them: a plan whose every step is a bare PASS with no market
    orders was never recorded, however many steps long it is.
    """
    filled = sum(1 for a in plan if (a.get("farmer") or ["PASS"])[0] != "PASS")
    hands = sum(len(a.get("hands") or []) for a in plan)
    orders = sum(len(a.get("market") or []) for a in plan)
    first = next((i for i, a in enumerate(plan)
                  if (a.get("farmer") or ["PASS"])[0] != "PASS"
                  or (a.get("market") or [])), None)
    last = next((len(plan) - 1 - i for i, a in enumerate(reversed(plan))
                 if (a.get("farmer") or ["PASS"])[0] != "PASS"
                 or (a.get("market") or [])), None)
    return (f"steps={len(plan)} farmer-acting={filled} hand-slots={hands} "
            f"market-orders={orders} first-active={first} last-active={last}")


def shape(plan):
    """The labour's density, in the same terms the published plans were read in.

    Reported here so a recording says at once how it compares: the top public
    plan does 2.07 jobs every time it stops, walks 1.99 steps between stops and
    spends 43% of its actions walking, with its animals ringed one or two tiles
    from the shed.
    """
    import statistics
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    import route_shape
    import layout

    streams = route_shape.unit_streams(plan)
    work, move = [], []
    for ops in streams.values():
        work += route_shape.runs(
            ops, lambda o: o not in route_shape.MOVES and o not in route_shape.IDLE)
        move += route_shape.runs(ops, lambda o: o in route_shape.MOVES)
    total = sum(len(o) for o in streams.values())
    moves = sum(1 for ops in streams.values() for o in ops if o in route_shape.MOVES)
    idle = sum(1 for ops in streams.values() for o in ops if o in route_shape.IDLE)

    access = set(layout.shed_access())
    centre = (4.5, 4.5)
    near, far = 0, 0
    for _s, _i, pos, op, _a in layout.walk(plan):
        if op in route_shape.MOVES or op in route_shape.IDLE:
            continue
        d = max(abs(pos[0] - centre[0]), abs(pos[1] - centre[1]))
        if d <= 2.5 or pos in access:
            near += 1
        else:
            far += 1

    def mean(xs):
        return statistics.mean(xs) if xs else float("nan")

    worked = near + far
    return (f"jobs-per-arrival={mean(work):.2f} steps-per-trip={mean(move):.2f} "
            f"walking={100.0 * moves / max(1, total):.0f}% "
            f"idle={100.0 * idle / max(1, total):.0f}% "
            f"work-within-2-of-shed={100.0 * near / max(1, worked):.0f}%")


def emit(plan, out_path):
    body = REPLAY_TEMPLATE.replace("__PLAN__", json.dumps(plan))
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(body)
    return out_path


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--a", help="agent to record (path under kaggriculture/)")
    ap.add_argument("--b", default="starter", help="opponent")
    ap.add_argument("--seed", type=int, default=3000)
    ap.add_argument("--steps", type=int, default=720)
    ap.add_argument("--side", type=int, default=0, choices=(0, 1))
    ap.add_argument("--emit", help="plan JSON to turn into an agent file")
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    if args.emit:
        with open(args.emit, encoding="utf-8") as f:
            plan = json.load(f)
        print("EMITTED", emit(plan, args.out), "steps", len(plan))
        return 0

    if not args.a:
        ap.error("--a is required unless --emit is given")
    plan, money = record(os.path.join(HERE, args.a) if os.path.exists(
        os.path.join(HERE, args.a)) else args.a, args.b, args.seed,
        args.steps, args.side)
    with open(args.out, "w", encoding="utf-8") as f:
        json.dump(plan, f)
    print(f"RECORDED money={money:.0f} -> {args.out}")
    print("PLAN " + describe(plan))
    print("SHAPE " + shape(plan))
    return 0


if __name__ == "__main__":
    sys.exit(main())
