# Deep Past Challenge — ByT5 Multi-Temperature MBR Ensemble v6
#
# Strategy:
# - Base model: mattiaangeli/byt5-akkadian-mbr-v2 (pre-trained on competition data)
# - NO fine-tuning — all GPU time invested in superior inference
# - Multi-temperature MBR: T=0.6, 0.8, 1.0 → 20 samples × 3 temps = 60 candidates/sentence
# - Unified chrF++ MBR selection across all 60 candidates
# - Context window: ±3 surrounding lines with [CURRENT] marker
# - TF-IDF similarity fallback for low-confidence translations
# - Disk usage: near-zero (inference only)
#
# Evaluation: BLEU + chrF++
# Competition: deep-past-initiative-machine-translation
#
# Generated by generate_notebook.py
