# Deep Past Challenge — ByT5 + MBR Fine-tuning v5
#
# Strategy:
# - Base model: mattiaangeli/byt5-akkadian-mbr-v2 (pre-trained on competition data)
# - Extra training: ORACC parallel corpus + enriched data (~2x more data)
# - Context window: ±2 surrounding lines with [CURRENT] marker
# - Decoding: MBR (Minimum Bayes Risk) with chrF++ utility (12 samples)
# - Disk optimization: save_total_limit=1, checkpoint cleanup after training
# - Evaluation: BLEU + chrF++
# Competition: deep-past-initiative-machine-translation
#
# Generated by generate_notebook.py
